version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: finance-ai-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_ai
    ports:
      - "5432:5432"
    volumes:
      - ./.postgress-data:/var/lib/postgresql/data

volumes:
  .postgres-data:
